version: 2
jobs:
  build:
    working_directory: ~/AngularBDD
    docker:
      - image: circleci/node:6-browsers
    dependencies:
      cache_directories:
       - ~/nvm
    steps:
      - checkout
      - restore_cache:
          key: AngularBDD-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - run: sudo npm install -g karma
      - run: npm run webdriver-update
      - save_cache:
          key: AngularBDD-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a karma start karma.conf.js --single-run --browser=ChromeNoSandbox
      - run: xvfb-run -a npm run e2e -- --no-progress --config=protractor.conf.js
